#!/usr/bin/env bash
# sfp-display test

# Source global test env arg and test class env
test -f "${1}" && source "${1}" || echo "Could not source test environment" 

# Source specific test env
source "${0/\/t\///t/.}-setup" || exit 1

# Tests
uri() {
    # Set up a fake jpg to use
    testjpg="/tmp/sfp-test/fake.jpg"
    dd if=/dev/urandom of="${testjpg}" bs=512 count=2 2> /dev/null
    bash -c "sfp display \"${testjpg}\"" | grep "${uriTestPass}" > /dev/null
}
add uri

mode(){
    bash -c "sfp display -o zoom" | grep "${optTestPass}" > /dev/null
}
add mode

export retVal=
for test in ${tests};  do
    logNewTest "${test}" && "${test}" && continue
    retVal=${?} 
    echo "=== FAILURE: '${test}' test failed (return value ${retVal})" 
done
exit ${retVal}
