#!/usr/bin/env bash
# sfp-fe (front-end) test

commandMustExist(){
    bash -c "sfp" > /dev/null
}
add commandMustExist

sfpMustListSubcommands() {
    bash -c "sfp" | grep 'subcommands' > /dev/null
}
add sfpMustListSubcommands

sfpMustListBuiltins() {
    # stats is a built-in
    bash -c "sfp" | grep 'stats' > /dev/null
}
add sfpMustListBuiltins

mockExtensionsMustWork() {
    # Sub commands (extensions) must be callable
    testSubc="/tmp/sfp-test/sfp-test"
    mkdir -p "$(dirname "${testSubc}")"
    cat > ${testSubc} <<EOS
#!/usr/bin/env bash
function sfp-test() {
    echo Tests are magic
}
EOS
    chmod +x "${testSubc}"
    bash -c "export 'PATH=${PATH}:$(dirname "${testSubc}")'; sfp test"  | grep magic > /dev/null
}
add mockExtensionsMustWork

# Also indirectly tests sourcing of global config
subcommandsReceiveUserConfigFile() {
    # Set up subcommand {
    testSubc="/tmp/sfp-test/sfp-test"
    mkdir -p "$(dirname "${testSubc}")"
    cat > ${testSubc} <<EOS
#!/usr/bin/env bash
function sfp-test() {
    echo \${TEST_USER_VAR}
}
EOS
    chmod +x "${testSubc}"
    # }
    # Set up signal var in shufflepaper.conf
    cat > ${XDG_CONFIG_HOME}/shufflepaper/user.conf <<EOS
#!/usr/bin/env bash
export TEST_USER_VAR="nice 2 meet u, i'm a signal value"
EOS
    
    bash -c "export 'PATH=${PATH}:$(dirname "${testSubc}")'; sfp test" | grep 'signal' > /dev/null
}
add subcommandsReceiveUserConfigFile
