#!/usr/bin/env bash
# sfp-fe (front-end) test

# Source global test env arg and test class env
test -f "${1}" && source "${1}" || echo "Could not source test environment" 

# Command must exist
bash -c "sfp" > /dev/null

# Command must list subcommands
bash -c "sfp" | grep 'subcommands' > /dev/null

# Command must list built in subcommands, e.g. stats
bash -c "sfp" | grep 'stats' > /dev/null

# Sub commands (extensions) must be callable
testSubc="/tmp/sfp-test/sfp-test"
mkdir -p "$(dirname "${testSubc}")"
cat >> ${testSubc} <<EOS
#!/usr/bin/env bash
function sfp-test() {
    echo Tests are magic
}
EOS
chmod +x "${testSubc}"
bash -c "export 'PATH=${PATH}:$(dirname "${testSubc}")'; sfp test"  | grep magic > /dev/null
