#!/usr/bin/env bash
# sfp-fe (front-end) test

commandMustExist(){
    bash -c "sfp" > /dev/null
}
add commandMustExist

sfpMustListSubcommands() {
    bash -c "sfp" | grep 'subcommands' > /dev/null
}
add sfpMustListSubcommands

sfpMustListBuiltins() {
    # stats is a built-in
    bash -c "sfp" | grep 'stats' > /dev/null
}
add sfpMustListBuiltins

mockExtensionsMustWork() {
    # Sub commands (extensions) must be callable
    testSubc="/tmp/sfp-test/sfp-test"
    mkdir -p "$(dirname "${testSubc}")"
    cat >> ${testSubc} <<EOS
#!/usr/bin/env bash
function sfp-test() {
    echo Tests are magic
}
EOS
    chmod +x "${testSubc}"
    bash -c "export 'PATH=${PATH}:$(dirname "${testSubc}")'; sfp test"  | grep magic > /dev/null
}
add mockExtensionsMustWork
