#!/usr/bin/env -S -i bash

test -f "${1}" && source "${1}" || echo "Could not source test environment" 

uriTestPass="valid-uri"
optTestPass="options received"

# gsettings interceptor
function gsettings() {
    if [[ "${3}" == "picture-uri" ]]; then
        if [[ -f "${4/file:\/\//}" ]]; then
            echo
        fi
    elif [[ "${3}" == "picture-opions" ]]; then
        if [[ ! -z "${4}" ]]; then
            echo ${optTestPass}
        fi
    fi
}
export -f gsettings

# dbus-launch interceptor
function dbus-launch(){
    echo "DBUS_LAUNCH=TEST"
}
export -f dbus-launch

# Set up a fake jpg to use
testjpg="/tmp/sfp-test/fake.jpg"
dd if=/dev/urandom of="${testjpg}" bs=512 count=2 2> /dev/null

bash -c "sfp display \"${testjpg}\"" | grep "${uriTestPass}" > /dev/null

bash -c "sfp display -o zoom" | grep "${optTestPass}" > /dev/null
